### PR TITLE
Add Debian support

### PR DESCRIPTION
**Pull request by n-rodriguez**

### CODE REVIEW

**Comment by awojtczyk** [comment]
Going to resolve the conflicts, quickly check it out and merge. Or you are working on something here @n-rodriguez ?

**Comment by n-rodriguez** [comment]
@awojtczyk I let you handle the conflicts and the merge :+1:

**Comment by awojtczyk** [comment]
> @awojtczyk I let you handle the conflicts and the merge 👍

@n-rodriguez could you grant me the permissions to write into this branch, please?

**Comment by n-rodriguez** [comment]
> @n-rodriguez could you grant me the permissions to write into this branch, please?

@awojtczyk  done

**Comment by awojtczyk** [comment]
Thank you @n-rodriguez

**Pull request merged**
