### PR TITLE
show message when error occurs

### PR DESCRIPTION
**Pull request by eslizn**

### CODE REVIEW

**Comment by woudsma** [comment]
Thanks for your contribution @eslizn.
I've changed the base branch to develop so it can be tested.

**Comment by awojtczyk** [comment]
@woudsma @eslizn 
I would rather do something like this:

```sh
# Outputs install log line
function setup_log() {
  if $SHOW_LOGS; then
    echo -e "\033[1;32m$*\033[m"
  fi
}

SHOW_LOGS=true	
function wordwrap() {
  if $SHOW_LOGS; then
    echo -e "\n"
  fi
}

```

then it can be used like that:

```sh
if [ "$(id -u)" != "0" ]; then
  setup_log "❌ Sorry! This script must be run as root." 1>&2
  exit 1
fi`

**Comment by woudsma** [comment]
That seems like a better option indeed, do you want to add it to `src/lib/functions` @awojtczyk ?

**Comment by awojtczyk** [comment]
Yup, as I'm working already on some refactor of our bash scripts :)

**Pull request merged**
